apiVersion: v1
kind: Service
metadata:
  name: java-demo-svc
  labels:
    app: java
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  labels:
    app: java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: svilambi/demo:latest
        ports:
        - containerPort: 8888
