name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Step 1 - List Files
      run: |
        pwd
        ls -a
    - name: Step 2 - Checkout
      uses: actions/checkout@v1
    - name: Step 3 - List Files After Checkout
      run: |
        pwd
        ls -a
    - name: Step 4 - Versions
      run: |
        java -version
        echo "just to test"
        gradle -version
    - name: Step 5 - build and jar
      run: |
        gradle bootjar
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
