name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Step 1 - List Files
      run: |
        pwd
        ls -a
    - name: Step 2 - Versions
      run: |
        java -version
        echo "just to test"
        gradle -version
    - name: Step 3 - build and jar
      run: |
        gradle bootjar
    - name: Step 4 - Build the Docker image
      run: docker build . --file Dockerfile --tag svilambi/demo:$(date +%s)
      
    - name: Step 5 - Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ github.DOCKER_USERNAME }}
        password: ${{ github.DOCKER_PASSWORD }}
        
    - name: Step 6 - Build the Docker image to dockerhub
      run: docker push svilambi/demo:$(date +%s)